/*EL USE ACTIVA ESTA BASE DE DATOS*/

USE Viajes 
GO
SELECT * FROM VUELOS

SELECT DESTINO, ESCALA FROM VUELOS

/* SI ES DOS O MAS PALABRAS SE USAN COMILLAS*/
/* SE USA COMILLA SIMPLE EN BASE DE DATOS*/
/* WHERE ES UNA CONDICION*/
SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE DESTINO='paris' AND ESCALA='LA PAZ';

SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE DESTINO='paris' OR ESCALA='LA PAZ'and valor_$/687>117;

/* el parentesis da prioridad*/
SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE (DESTINO='paris' OR ESCALA='LA PAZ')and valor_$/687>117;

SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE DESTINO='paris' OR ESCALA='LA PAZ'order by ESCALA;

SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE DESTINO='paris' OR ESCALA='LA PAZ'order by ESCALA desc

SELECT ESCALA,DESTINO, VALOR_$/687 AS VALOR FROM VUELOS 
WHERE DESTINO='paris' OR DESTINO='BARCELONA'order by ESCALA desc

SELECT * FROM AEROLINEAS
SELECT * FROM VUELOS

/* ON ES CRITERIO */
SELECT VUELOS.CODIGO, NOMBRE, DESTINO, ESCALA
FROM VUELOS INNER JOIN AEROLINEAS ON VUELOS.CODIGO=AEROLINEAS.CODIGO;

/*SIN INNER JOIN: TOMA LOS DOS Y LOS JUNTA CON TODOS*/
SELECT VUELOS.CODIGO, NOMBRE, DESTINO, ESCALA
FROM VUELOS, AEROLINEAS 
WHERE VUELOS.CODIGO=AEROLINEAS.CODIGO
 

select nombre,
CASE numero
	WHEN 1 THEN 'BOEING 747'
	WHEN 2 THEN 'AIRBUS a380'
	ELSE 'JUMBO' -- Valor por defecto
END
FROM AEROLINEAS;


/*SI INVOCO CAMPOS SIN REPETIR EL SISTEMA RECONOCE A CUAL TABLA PERTENECE*/
/*HAY BIFURCACION SIMPLE*/
SELECT NOMBRE, DESTINO, ESCALA, VALOR_$,
CASE DESTINO
	WHEN'PARIS' THEN VALOR_$*0.06 
	WHEN'ROMA' THEN VALOR_$*0.07
	WHEN'LONDRES' THEN VALOR_$*.09
ELSE 
    VALOR_$*0.04
END
    AS VALORAGREGADO

/*SI VALORAGREGADO SE SEPARA VA CON COMILLAS SIMPLES*/
FROM VUELOS INNER JOIN AEROLINEAS
/*CRITERIO DE UNION ON*/
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
/*GROUP BY ANTES EL ORDER BY. EL OREDER BY VA AL FINAL*/
ORDER BY NOMBRE DESC

-----------------

SELECT NOMBRE, DESTINO, ESCALA, VALOR_$,

CASE DESTINO
	WHEN'PARIS' THEN VALOR_$*0.06 
	WHEN'ROMA' THEN VALOR_$*0.07
	WHEN'LONDRES' THEN VALOR_$*.09
ELSE 
    VALOR_$*0.04
END
    AS VALORAGREGADO,
 
CASE DESTINO
	WHEN'PARIS' THEN VALOR_$*0.06 +VALOR_$
	WHEN'ROMA' THEN VALOR_$*0.07 +VALOR_$
	WHEN'LONDRES' THEN VALOR_$*.09 +VALOR_$
 ELSE
  VALOR_$*0.04+VALOR_$
END
    AS VALORTOTAL
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
ORDER BY NOMBRE DESC


--------------------

SELECT NOMBRE,DESTINO
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE VUELOS.CODIGO='IBE380' OR VUELOS.CODIGO='SKY380' OR VUELOS.CODIGO='LAN380'
/*WHERE VUELOS.CODIGO LIKE '%380'*/
 /*WHERE VUELOS.CODIGO LIKE '___380'* SON COMODINES*/
 
SELECT NOMBRE,DESTINO
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE VUELOS.CODIGO LIKE '%380'
 
----------------------

SELECT NOMBRE,DESTINO,ESCALA
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE VALOR_$>=100000 AND IMPUESTO*690<10359

-----------------------

SELECT VUELOS.CODIGO, NOMBRE,VALOR_$, CASE VUELOS.CODIGO 
WHEN 'TAM747' THEN VALOR_$*.12 
WHEN 'IBE389' THEN VALOR_$*.15
WHEN 'LAN747' THEN VALOR_$*0.07
ELSE VALOR_$*0.04
END AS 'IMPUESTO LOZA'
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO


7)	Mostrar NOMBRE, DESTINO, ESCALA , IMPUESTO en $ (dólar a $520) VALOR, VALOR
 depende de NUMERO:
Si NUMERO = 1 VALOR = VALOR_$ + VALOR_$*4%
Si NUMERO = 2 VALOR = VALOR_$ + VALOR_$*5%
Si NUMERO = 3 VALOR = VALOR_$ + VALOR_$*7%


SELECT NOMBRE, DESTINO, ESCALA, IMPUESTO * 520 AS 'IMP.EN DOLAR', VALOR_$,

CASE NUMERO
	WHEN 1 THEN VALOR_$+VALOR_$*0.04 
	WHEN 2 THEN VALOR_$+VALOR_$*0.05
	WHEN 3 THEN VALOR_$+VALOR_$*0.07
END
    AS NUEVOVALOR_$

FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO

---------------------------
SELECT * FROM VUELOS
INSERT INTO VUELOS VALUES ('LAN747', 'ATENAS', 'LIMA', '110000','12');


SELECT NOMBRE, DESTINO, ESCALA, VALOR_$,IMPUESTO,IMPUESTO * 680 AS IMPUESTOENPESOS,
CASE DESTINO
	WHEN'PARIS' THEN VALOR_$*0.06 
	WHEN'ROMA' THEN VALOR_$*0.07
	WHEN'LONDRES' THEN VALOR_$*0.09
	WHEN'ATENAS' THEN VALOR_$*0.05
	WHEN'BARCELONA' THEN VALOR_$*0.08
ELSE 
    VALOR_$*0.04
END
  
    AS VALORAGREGADO
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE (IMPUESTO>=10 AND IMPUESTO<=20)
ORDER BY NOMBRE DESC

--1)Mostrar nombre, destino de todos los vuelos que sean modelo 380
 -- y su capacidad sea superior a 400 pasajeros
 --(se puede usar in like)
 
SELECT nombre, DESTINO, VUELOS.CODIGO FROM VUELOS INNER JOIN AEROLINEAS
ON 
VUELOS.CODIGO='IBE380'or VUELOS.CODIGO='SKY380'or 
VUELOS.CODIGO='LAN380'
WHERE BUSINESS+PRIMERA+TURISTA>400

SELECT nombre, DESTINO, VUELOS.CODIGO FROM VUELOS INNER JOIN AEROLINEAS
on
BUSINESS+PRIMERA+TURISTA>400
where vuelos.CODIGO like '%380'
order by NOMBRE

SELECT nombre, DESTINO, VUELOS.CODIGO FROM VUELOS INNER JOIN AEROLINEAS
on VUELOS.CODIGO=AEROLINEAS.CODIGO
where BUSINESS+PRIMERA+TURISTA>400 and vuelos.CODIGO like '%380'
order by NOMBRE

--profe
SELECT NOMBRE,DESTINO FROM AEROLINEAS AS AA INNER JOIN VUELOS AS BB
ON AA.CODIGO=BB.CODIGO
WHERE PRIMERA+BUSINESS+TURISTA>400
order by NOMBRE

--2)Mostrar nombre. Destino, escala de todos los vuelos cuyo valor_$ sea mayor
-- igual a 100000 e impuesto_US sea mayor a 7900 y menor a $10359  
 
---primer intento
SELECT nombre, DESTINO, ESCALA,VALOR_$,IMPUESTO FROM VUELOS INNER JOIN AEROLINEAS
ON VALOR_$>=100000 and ((IMPUESTO*700)>7900 and (IMPUESTO*700)<10359)
order by NOMBRE

---segundo intento
SELECT nombre, DESTINO, ESCALA,VALOR_$,IMPUESTO FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
where VALOR_$>=100000 and ((IMPUESTO*700)>7900 and (IMPUESTO*700)<10359)
order by NOMBRE

----EL INNER JOIN Y EL ON VAN JUNTOS,EN EL CASO DE ARRIBA(primer intento) HACE UN INNER CROSS
---PROFE
SELECT NOMBRE,DESTINO,ESCALA FROM AEROLINEAS AS AA INNER JOIN VUELOS AS BB
ON AA.CODIGO=BB.CODIGO
WHERE VALOR_$>=100000 AND (IMPUESTO*700>7900 AND IMPUESTO*700<10359)


--3.- Mostrar código, nombre, valor_$, Impuesto Loza (es un impuesto que paga
-- el pasajero al aeropuerto) el impuesto depende de código, 
--si es TAM747, impuesto 12% de valor_$, IBE389  15%, LAN747 es  7%, otros casos 4% 

SELECT VUELOS.CODIGO,nombre,VALOR_$,IMPUESTO,
CASE VUELOS.CODIGO
	WHEN'TAM747' THEN VALOR_$*0.12
	WHEN'IBE389' THEN VALOR_$*0.15
	WHEN'LAN747' THEN VALOR_$*0.07
ELSE 
    VALOR_$*0.04
END
AS 'impuesto loza'
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
ORDER BY NOMBRE DESC

---PROFE
---EL CASE VA DENTRO DEL SELECT
SELECT VUELOS.CODIGO, NOMBRE,VALOR_$,
CASE VUELOS.CODIGO
	WHEN'TAM747' THEN VALOR_$*0.12
	WHEN'IBE389' THEN VALOR_$*0.15
	WHEN'LAN747' THEN VALOR_$*0.07
ELSE 
    VALOR_$*0.04
END
AS 'impuesto loza'
FROM AEROLINEAS INNER JOIN VUELOS  
ON AEROLINEAS.CODIGO=VUELOS.CODIGO
ORDER BY NOMBRE DESC


---4.- Reajustar todos los valores (valor_$) en un 4,5%.

UPDATE VUELOS SET VALOR_$=VALOR_$*1.045
SELECT * FROM VUELOS

UPDATE VUELOS SET VALOR_$=VALOR_$/1.045


---PROFE
UPDATE VUELOS SET VALOR_$=VALOR_$+VALOR_$*0.045


/*5.- Mostrar NOMBRE, DESTINO, ESCALA, VALOR_$ y VALORAGREGADO,
 el resultado mostrar ordenado por nombre descendentemente.
 VALORAGREGADO =  VALOR_$ * % ,  el % depende de DESTINO según lo siguiente: 
 PARIS = 6%, ROMA= 7%, LONDRES = 9%, cualquier otro destino corresponde a 4% */
 
SELECT Nombre,DESTINO,ESCALA,VALOR_$,
CASE DESTINO
	WHEN'PARIS' THEN VALOR_$*0.06
	WHEN'ROMA' THEN VALOR_$*0.07
	WHEN'LONDRES' THEN VALOR_$*0.09
ELSE 
    VALOR_$*0.04
END
AS 'VALOR AGREGADO'
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
ORDER BY NOMBRE DESC

---6.- Actualizar los datos de destino, donde todos deben ser en minúsculas.

UPDATE VUELOS SET DESTINO=LOWER(DESTINO)
UPDATE VUELOS SET DESTINO=UPPER(DESTINO)

SELECT * FROM VUELOS


---7.- Mostrar nombre, escala y total a pagar (valor_$ + impuestos_US)
 ---con escala en Sud-América
 
SELECT Nombre,ESCALA,VALOR_$,IMPUESTO,VALOR_$ + IMPUESTO AS 'TOTAL A PAGAR'
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE ESCALA='BOGOTA'

---PROFE
SELECT Nombre,ESCALA,VALOR_$ + IMPUESTO AS 'TOTAL A PAGAR'
FROM VUELOS INNER JOIN AEROLINEAS
ON VUELOS.CODIGO=AEROLINEAS.CODIGO
WHERE ESCALA='BOGOTA' OR 
ESCALA='LA PAZ'OR
ESCALA='CARACAS'OR
ESCALA='LIMA' OR
ESCALA='QUITO'
